Make MetricsManager work pre ICS
MetricsManager being static and referencing Application.ActivityLifecycleCallbacks caused instant NoClassDefFoundErrors on Android earlier ICS. The lint warning which would have protected against this was muted by a way too broad @TargetApi annotation.
This approach uses a private class to implement the Application.ActivityLifecycleCallbacks interface which causes no static loading and dependency on the framework interface. Everything works as before, except for the SDK now progressively enhancing apps with automatic session tracking on ICS and newer.